create table Person (
                        id int generated by default as identity primary key,
                        name varchar(50) unique,
                        b_year int check ( b_year > 1909 and b_year < 2020 )
)

create table Book (
                      id int generated by default as identity primary key,
                      owner_id int references person (id) on delete set null,
                      title varchar(50) not null,
                      author varchar(50) not null,
                      year int check ( year > 1699 and year < 2100 )
)